### PR TITLE
LPS-40142 Updated Vaadin to 7.1.7

### PR DESCRIPTION
**Pull request by johndevs**
Updates Vaadin dependency to use the latest Vaadin 7.1.7 release. Includes jsoup as a new non-vaadin dependency.

### CODE REVIEW

**Comment by edgonzales** [comment]
Hi @johndevs 
Thanks for creating a new pull request. One very important step I forgot to mention. Please access LPS-40142 and change the status to Contributed Solution, check the Liferay Contributor's Agreement, and paste your new pull request link. Thanks again @johndevs for your contribution!

**Comment by johndevs** [comment]
Any chance of still getting this into 6.2? 

Would be great if Vaadin-Liferay developers would be able to use Vaadin 7 out of the box with Liferay 6.2 :)

**Comment by mikakoivisto** [comment]
Can't be merged. Please see my comments on the ticket.

**Comment by johndevs** [comment]
Added some comments to the ticket.

The baseline being that vaadin-shared-deps could be split up into its original jars found at https://github.com/vaadin/vaadin-deps/tree/master/shared/deps. 

The only problem I see is the json library. Vaadin ships with the json library found via maven http://mvnrepository.com/artifact/org.json/json and liferay is shipping with a custom built version from https://github.com/douglascrockford/JSON-java as far as I can tell. Is Liferay using any custom functionality of that implementation that would hinder using the version from maven?

**Comment by johndevs** [comment]
Any idea's about the json dependency issue from the liferay team? Should I go ahead and split up the vaadin-deps into seperate jars and still include the json library in the patch or should I omit it and hope for the best that the json lib used by liferay is compatible with Vaadin?

**Comment by johndevs** [comment]
Created a new pull requst for @mikakoivisto https://github.com/mikakoivisto/liferay-portal/pull/54/commits

**Pull request closed without merging**
