### PR TITLE
[TECH SUPPORT] LPS-28053

### PR DESCRIPTION
**Pull request by matethurzo**
Hey Juan, this is basically a JAR file update with a path built in it. You can find the exact details in the LPS ticket. Thanks, Mate

### CODE REVIEW

**Comment by caorongjin** [comment]
@matethurzo, @zsoltbalogh, @juanferrub while this makes sense to patch CMIS-527, can we do it against 0.7?  Reason being we are currently running 0.6, while 0.7 is the latest distributed version (a version I've been meaning to upgrade to for a while).  CMIS-527 is a patch that is fixed in 0.8 so when we actually upgrade to 0.8, we will automatically have that fix.  But if I or somebody else upgrade to 0.7 in the meantime, we need to reapply the patch for 0.7 and, in essence, reapply LPS-28053.

**Comment by zsoltbalogh** [comment]
@caorongjin Well, I'm working for resolving a support issue. I can't make decisions like upgrading a plugin. It would be great if we could bring this fix in and backport it and later fix the version upgrade which can cause regressions.

What do you think?

Thanks,
Zsolt

**Comment by caorongjin** [comment]
@zsoltbalogh I suppose it makes sense from a process perspective to fix this issue and backport it.  Then, in a separate ticket, upgrade the library with 0.7 and patch it.

I just thought it would streamline things… although, in hindsight, I suppose it doesn't help in terms of the support ticket.  So yah, let's just do what you are suggesting.  Sorry to interrupt.  :)

**Comment by zsoltbalogh** [comment]
@caorongjin I believe that you are right as for making the product better, it would be definitely better to upgrade the library. We could resolve this problem by forward-porting, but that discussion should not happen in a pull req. :)

**Comment by caorongjin** [comment]
@zsoltbalogh Point taken.  Again, sorry to interrupt.

**Comment by juanferrub** [comment]
Sent! https://github.com/brianchandotcom/liferay-portal/pull/5837
Thanks, guys

**Pull request closed without merging**
