### PR TITLE
LPS-33356

### PR DESCRIPTION
**Pull request by samuelkong**

### CODE REVIEW

**Comment by samuelkong** [comment]
@NorbertKocsis @moltam89 

Can you provide details on what you're trying to do with the changes in VerifyBlog?

**Comment by NorbertKocsis** [comment]
@samuelkong 

One of the vulnerabilities resides in the default blog DDMTemplate which is stored in the database, so we need a way  to update it, and we try to do it during the verify process.
It's similar to what happens in AddDefaultDDMTemplatesAction.

**Comment by samuelkong** [comment]
@NorbertKocsis 

Templates are new for 6.2, correct? So no one has the default template yet, which means there's no need to fix the template in the database, correct?

**Comment by NorbertKocsis** [comment]
You are right. Sorry!

**Comment by samuelkong** [comment]
I'm closing this and I'll send to Brian.

**Comment by samuelkong** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/9621

**Pull request closed without merging**
